name: thaisl
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Beforeflash.png
    - assets/images/camera_clicked.png
    - assets/images/camera.png
    - assets/images/cameraswap.png
    - assets/images/cameratest.png
    - assets/images/favorite.png
    - assets/images/flash.png
    - assets/images/frame.png
    - assets/images/menu.png
    - assets/images/swap.png
